IbuildingsEsiDemoBundle:
    resource: "@IbuildingsEsiDemoBundle/Resources/config/routing.yml"
    prefix:   /esi-demo

# Internal routing configuration to handle ESI
_internal:
   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
   prefix:   /_internal
